// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeforeCleanArchitecture.Models;

[Table("Book")]
public partial class Book
{
    /// <summary>
    /// 도서고유ID
    /// </summary>
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; } = null!;

    /// <summary>
    /// 도서 제목
    /// </summary>
    [StringLength(50)]
    public string Title { get; set; } = null!;

    /// <summary>
    /// 도서 설명
    /// </summary>
    [StringLength(50)]
    public string Description { get; set; } = null!;

    /// <summary>
    /// 도서 작가
    /// </summary>
    [StringLength(50)]
    public string Author { get; set; } = null!;

    /// <summary>
    /// 보유 수량
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// 수정일시
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 생성일시
    /// </summary>
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<Rent> Rents { get; set; } = new List<Rent>();
}