// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeforeCleanArchitecture.Models;

[Table("User")]
public partial class User
{
    /// <summary>
    /// 유저고유ID
    /// </summary>
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; } = null!;

    /// <summary>
    /// 성명
    /// </summary>
    [StringLength(50)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 상태 (0: 가입대기, 1: 활동, 2: 정지)
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// 이메일
    /// </summary>
    [StringLength(50)]
    public string? Email { get; set; }

    /// <summary>
    /// 수정일시
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 생성일시
    /// </summary>
    public DateTime CreatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Rent> Rents { get; set; } = new List<Rent>();
}